export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_STUDENT = 'SET_CURRENT_STUDENT';
export const GET_PROFILE_STUDENT = 'GET_PROFILE_STUDENT';
export const GET_PROFILES_STUDENT = 'GET_PROFILES_STUDENT';
export const PROFILE_STUDENT_LOADING = 'PROFILE_STUDENT_LOADING'

export const PROFILE_STUDENT_NOT_FOUND = 'PROFILE_STUDENT_NOT_FOUND'

export const CLEAR_CURRENT_STUDENT_PROFILE = 'CLEAR_CURRENT_STUDENT_PROFILE'

//company action
 
export const SET_CURRENT_COMPANY = 'SET_CURRENT_COMPANY';
export const GET_PROFILE_COMPANY = 'GET_PROFILE_COMPANY';
export const PROFILE_COMPANY_LOADING = 'PROFILE_COMPANY_LOADING';
export const CLEAR_CURRENT_COMPANY_PROFILE = 'CLEAR_CURRENT_COMPANY_PROFILE';
export const GET_PROFILES_COMPANY = 'GET_PROFILES_COMPANY ';

export const SET_CURRENT_ADMIN = 'SET_CURRENT_ADMIN';
export const CLEAR_CURRENT_ADMIN = 'CLEAR_CURRENT_ADMIN'

