export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_STUDENT = 'SET_CURRENT_STUDENT';
export const GET_PROFILE_STUDENT = 'GET_PROFILE_STUDENT';
export const GET_PROFILES_STUDENT = 'GET_PROFILES_STUDENT';
export const PROFILE_STUDENT_LOADING = 'PROFILE_STUDENT_LOADING'

export const PROFILE_STUDENT_NOT_FOUND = 'PROFILE_STUDENT_NOT_FOUND'

export const CLEAR_CURRENT_STUDENT_PROFILE = 'CLEAR_CURRENT_STUDENT_PROFILE'

